title: RyansSwell
author: Ryan Anderson
email: ryan0425@msn.com
description: > # this means to ignore newlines until "baseurl:"
    Looking for new coding opportunities and new challenges! 
    I am still a beginner but I know I can do anything!
    
    
# social links
github_username: Ryansswell

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
